### PR TITLE
add support for Instagram

### PR DESCRIPTION
**Pull request by paullang**
I'd like to add Instagram to your list of supported providers.

### CODE REVIEW

**Comment by 7200rpm** [comment]
@paullang Noob question, but how do you generate/compile the other files from the instagram.ts file? I"m trying to add in Linkedin and not sure where to start modifying files...

**Comment by paullang** [comment]
@7200rpm in the package.json the package.json in this repo you can see what build scripts are configured to run via npm.  So you can use the following if you add or modify *.ts files.
`npm run tsc`

If you just want to use my instagram provider as-is while waiting for @nraboy to merge this PR and publish to the NPM registry, then you can add the following to your application's package.json so that that npm CLI will download mine from github instead of the official one from NPM.
"dependencies": {
  "ng2-cordova-oauth": "paullang/ng2-cordova-oauth#instagram"
}

If you are concerned about me deleting my repo, then you can fork my repo and reference your own
"dependencies": {
  "ng2-cordova-oauth": "7200rpm/ng2-cordova-oauth#instagram"
}

BTW, I'm considering switching to Auth0 for my own project
http://blog.ionic.io/ionic-2-and-auth0/

**Comment by nraboy** [comment]
Hey for whatever reason GitHub didn't notify me about this PR.  I'm going to look at it today and get it merged.

Best,

**Comment by nraboy** [comment]
Thank you for contributing!

**Pull request merged**
