### PR TITLE
Add vk.com provider

### PR DESCRIPTION
**Pull request by shanhaichik**

### CODE REVIEW

**Comment by nraboy** [comment]
I assume this is the same as https://github.com/nraboy/ng2-cordova-oauth/pull/37, correct?

Have you tested this and confirmed it worked?

Best,

**Comment by shanhaichik** [comment]
Hi, @nraboy 
Yes, it's the same.
I made the request, but then I read that it is better in the branch development.

Tomorrow I will check again at work and confirm.
Okay?

**Comment by nraboy** [comment]
Yes, please verify with me that it works and I'll merge it.  I don't have a VK account so I cannot test it myself.

I'll trust what you tell me :-)

**Comment by shanhaichik** [comment]
Hi, @nraboy 
I checked and made corrections. Everything is working.
I made screenshots, if necessary.

Good luck.

**Comment by nraboy** [comment]
Thank you for contributing!

**Pull request merged**
