### PR TITLE
feat(platform): adds separate platforms for web and cordova apps

### PR DESCRIPTION
**Pull request by stalniy**
This allows to use library for both apps: cordova and web.
Also it adds test page which allows quickly test if library works for different providers. But before you will need to run `npm run build`

### CODE REVIEW

**Comment by stalniy** [comment]
I updated docs, so will wait for a new version to be realised =)

**Comment by HR808830** [comment]
i was used this code ,then will be occure my error 

Uncaught TypeError: Cannot read property 'split' of undefined", source: file:///android_asset/www/cordova.js

**Comment by stalniy** [comment]
Current PR doe sn't contain `.split` invocation. I will re-check it one more time today but everything should be fine

**Comment by stalniy** [comment]
@nraboy I've just tested all 6 providers (Instagram, LinkedIn, Google, Facebook, Imgur, Meetup) in both browser and cordova envs. Everything works as expected

**Comment by stalniy** [comment]
@nraboy is there something what I can do in order to speed up merge of this?

This is the last MR which I planned to do, so then I will switch to use your version instead of my fork

**Comment by nraboy** [comment]
Sorry for me lagging it.  I will do it tonight or this weekend.

**Comment by stalniy** [comment]
@nraboy just a reminder =)

**Comment by nraboy** [comment]
Sorry I've been so slow on this.  Been preoccupied with some local events.  I'll try to get this merged into `master` as soon as possible.

**Pull request merged**
