### PR TITLE
Add strava

### PR DESCRIPTION
**Pull request by jstoup111**
@nraboy

I've added support for Strava. This flow only gets the code from Strava and gives you the capability to handle how you want the access token from there.

See #7

Retrieving the access_token is as simple POSTing per their documentation.

curl -X POST https://www.strava.com/oauth/token \
    -F client_id=5 \
    -F client_secret=7b2946535949ae70f015d696d8ac602830ece412 \
    -F code=75e251e3ff8fff
This is safer since the clientID wouldn't be stored client side.

Updated per your comments.

### CODE REVIEW

**Comment by jstoup111** [comment]
Is this good to go? Would like to know when a merge and release with this might be available.

**Comment by nraboy** [comment]
Thanks for reminding me!

Just to confirm, have you tested this within an app?  Let me know and I'll get it merged.

Best,

**Comment by jstoup111** [comment]
Yea I was running it previously, before I wiped `node_modules` and forgot I wasn't pointing locally anymore.

**Comment by jstoup111** [comment]
Just a friendly bump. :)

**Comment by nraboy** [comment]
Sorry about taking so long.  Problem with so many GitHub projects is finding the time :-)

**Pull request merged**
