### PR TITLE
new provider - spotify

### PR DESCRIPTION
**Pull request by EduMiada**
Add support for Spotify.

Response type= token or code;
this.cordovaOauth = new CordovaOauth(new Spotify({clientId:'xxx',responseType:'token',appScope: ['user-read-email', 'user-read-private'],showDialog:'true' }));

### CODE REVIEW

**Comment by nraboy** [comment]
Hey @EduMiada,

Can you explain to me the purpose behind having response type of code?  That is for the explicit grant type option.

Please let me know the story.

Thanks,

**Comment by EduMiada** [comment]
Hi @nraboy,

I have a server side rest used by both mobile and web application. All interactions between my apps and spotify api is done through the server. That way I can connect to spotify once on any UI (web or mobile) and use the code and refresh token to get authorization token whenever necessary.

**Comment by nraboy** [comment]
Sorry for the 100 questions, but can you explain the showDialog and why two different options would be relevant in this plugin?

Other than that it looks good.  I assume you tested both the implicit and explicit?

**Comment by EduMiada** [comment]
Hey no problem, it's your baby you need to know whats going on :-)

You were right, the showDialog param doesn't make any difference in this plugin. 

Tested the changes and both implicit and explicit options.

**Comment by nraboy** [comment]
Thanks for understanding!  Trying to have good quality control to prevent another sketchy library on GitHub.

I saw you removed the `showDialog`.  Can you confirm that it is not required?  Once you do this, I will finally merge your PR :-)

**Comment by EduMiada** [comment]
The parameter is optional, I have tested after the changes.  :-)

**Comment by nraboy** [comment]
Thank you for contributing!

**Pull request merged**
